services:
  formapp:
    image: formapp
    build:
      context: .
      dockerfile: FormApp/Dockerfile
    ports:
      - "5093:5093"
      - "80:80"
      - "8080:8080"
    depends_on:
      - db

  db:
    restart: always
    container_name: db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=FormApp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 